import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ResQrunch',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <main>
          <div className="hidden md:flex md:justify-center md:items-center md:w-screen md:h-screen ">
            <h1>Application only available in mobile view!</h1>
          </div>
          <div className="block h-screen md:hidden">{children}</div>
        </main>
      </body>
    </html>
  );
}
